modLoader="javafml" #mandatory
# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[28,)" #mandatory (28 is current forge version)
# A URL to refer people to when problems occur with this mod
[[mods]] #mandatory
modId="vodkaplus" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Vodka+" #mandatory
authors="ImNotJahan" #optional
description='''
Adds vodka. That's about it.
'''
